DROP TABLE IF EXISTS vmoive;
CREATE TABLE vmoive(
  id INT(6) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  cover VARCHAR(255),
  title VARCHAR(255),
  mdec VARCHAR(255),
  playUrl VARCHAR(255)
) DEFAULT CHARSET=utf8;

